name: digi_patient
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_localization: ^0.1.10
  intl: ^0.17.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  another_flushbar: ^1.12.29
  fluttertoast: ^8.1.1
  provider: ^6.0.4
  auto_route: ^5.0.2
  flutter_screenutil: ^5.6.0
  screen_utils: ^0.0.1
  email_validator: ^2.1.17
  shared_preferences: ^2.0.15
#  google_fonts: ^3.0.1
  percent_indicator: ^4.2.2
  flutterzilla_fixed_grid: ^0.0.4
  carousel_slider: ^4.1.1
  curved_navigation_bar: ^1.0.3
  pin_code_fields: ^7.4.0
  image_picker: ^0.8.6
  font_awesome_flutter: ^10.2.1
  rflutter_alert: ^2.0.4
  animated_text_kit: ^4.2.2
  onboarding: ^3.1.0

  pdf: ^3.8.4
  flutter_pdfview: ^1.2.5
  path_provider: ^2.0.11
  printing: ^5.9.3
  file_picker: ^5.2.5
  path_drawing: any
  image_painter: ^0.4.6
  modal_bottom_sheet: ^2.1.2
  photo_view: ^0.14.0
  agora_uikit: ^1.0.4
  agora_rtc_engine: ^5.2.0
  date_format: ^2.0.7
  human_body_selector: ^0.0.1
  zoom_widget: ^2.0.0
  badges: ^3.0.2
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  build_runner:

  flutter_lints: ^2.0.0


flutter:
#  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 200
